### ISSUE TITLE
no util files

### ISSUE THREAD

**Issue by RyanCV** [nbansal90/Can-we-Gain-More-from-Orthogonality#1]
Hi, it gave error at this line: https://github.com/nbansal90/Can-we-Gain-More-from-Orthogonality/blob/8b39e476fd651234f58086952b00a06c401ed614/SVHN/train.py#L17

will you upload the whole folder for running your code? Thanks.

**Comment by nbansal90** [comment]
Hi Ryan!
I would suggest you to comment out that line and run. By the way, If you wish to save the result in the CSV file nonetheless, then Once you clone the repository, you need to create a path with **logs/** directory, as mentioned in the lines:
```
filename = 'logs/' + test_id + '.csv'
csv_logger = CSVLogger(args=args, fieldnames=['epoch', 'train_acc', 'test_acc'], filename=filename)
```
Hope that Helps!

Regards
Nitin
